# Oracle
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=app
quarkus.datasource.password=app
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1

# Hibernate (DEV)
quarkus.hibernate-orm.schema-management.strategy=update
# quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

# (opcional) CORS pra front separado depois
# quarkus.http.cors=true
# quarkus.http.cors.origins=http://localhost:5173,http://localhost:3000

